# Generated by Django 4.2.16 on 2024-11-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0002_alter_category_options_remove_customer_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="Fufu.jpg", null=True, upload_to="uploads/product/"
            ),
        ),
    ]
