# Generated by Django 4.2.16 on 2024-11-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0003_cart_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
