# Generated by Django 4.2.16 on 2024-12-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0006_profile_old_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="old_cart",
        ),
    ]
