# Generated by Django 4.2.16 on 2024-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0007_remove_profile_old_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
