# Generated by Django 4.2.16 on 2024-12-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date_shipped",
        ),
    ]
