# Generated by Django 4.2.16 on 2024-12-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_remove_order_date_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
